services:
  - type: web
    name: canteen-management
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn canteen.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"